#!/bin/bash

if [ "$2" == "ether" ]; then
#web3.fromWei(eth.getBalance(eth.accounts[0]),"ether")
echo "Printing balance in ETHER"
eval $(echo "curl --location --request POST 'localhost:8545' --header 'Content-Type: application/json' --data-raw '{\"jsonrpc\": \"2.0\",\"id\": 4,\"method\": \"eth_getBalance\",\"params\": [\"$1\",\"latest\"]}'")
else
eval $(echo "curl --location --request POST 'localhost:8545' --header 'Content-Type: application/json' --data-raw '{\"jsonrpc\": \"2.0\",\"id\": 4,\"method\": \"eth_getBalance\",\"params\": [\"$1\",\"latest\"]}'")
fi
