#!/bin/bash

eval $(echo "curl --location --request POST 'localhost:8545' --header 'Content-Type: application/json' --data-raw '{\"jsonrpc\": \"2.0\",\"id\": 4,\"method\": \"eth_getBalance\",\"params\": [\"$1\",\"latest\"]}'")
