#!/bin/bash

curl --location --request POST 'http://localhost:8545' --header 'Content-type: application/json' --data-raw '{"jsonrpc": "2.0","id": 6,"method": "personal_unlockAccount","params": ["0xe04bdc84194e37b4d961d4b1a83402105a4ddd0e","5uper53cr3t"]}'
